- name: Install python-setuptools
  yum: name={{ item }} state=installed
  with_items:
    - python-setuptools

- name: Install supervisor via easy_install
  sudo: yes
  shell: |
    easy_install supervisor

- name: Create supervisord directory
  sudo: yes
  file: path={{ item }} state=directory mode=u+rw,a+r owner=root group=root
  with_items:
    - /etc/supervisord.d
    - /var/log/supervisor/

- name: Create configuration files
  sudo: yes
  template: src={{ item }}.j2 dest=/etc/{{ item }} mode=u+rw,a+rx owner=root group=root
  with_items:
    - supervisord.conf
    - supervisord.d/example.conf
    - init.d/supervisord

- name: Register supervisord service
  sudo: yes
  shell: |
    chkconfig --add supervisord
    chkconfig supervisord on

- name: Run supervisord
  service: name=supervisord state=started enabled=yes
